services:

  backend:
    build:
      context: ./backend
    container_name: yieldsense-backend
    ports:
      - "8000:8000"
    environment:
      DB_HOST: host.docker.internal
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: yieldsense-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped