services:

  backend:
    build: .
    container_name: yieldsense-backend-container
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:Nireesha03@db:5432/yieldsense_db
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: yieldsense-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Nireesha03
      POSTGRES_DB: yieldsense_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: